workflow:
  general:
    type_map: [ H, O ]
    mass_map: [ 1.008, 15.999 ]
    max_iters: 2
    update_explore_systems: true

  train:
    deepmd:
      model_num: 4
      init_dataset: [ h2o-64-train ]
      input_template:
        model:
          descriptor:
            type: se_a  # modify according to your system
            sel:
            - 100
            - 100
            rcut_smth: 0.5
            rcut: 5.0
            neuron:
            - 25
            - 50
            - 100
            resnet_dt: false
            axis_neuron: 16
            seed: 1
          fitting_net:
            neuron:
            - 240
            - 240
            - 240
            resnet_dt: true
            seed: 1
        learning_rate:
          type: exp
          start_lr: 0.001
          decay_steps: 2000
        loss:
          start_pref_e: 0.02
          limit_pref_e: 2
          start_pref_f: 1000
          limit_pref_f: 1
          start_pref_v: 0
          limit_pref_v: 0
        training:
          numb_steps: 10000
          seed: 1
          disp_file: lcurve.out
          disp_freq: 1000
          save_freq: 1000
          save_ckpt: model.ckpt
          disp_training: true
          time_training: true
          profiling: false
          profiling_file: timeline.json

  label:
    cp2k:
      init_system_files: [ h2o-64-validation ]
      limit: 10
      input_template: !load_text ./config/cp2k.inp
      wfn_warmup_template: !load_text ./config/cp2k.inp

  explore:
    # lasp:
    #   input_template:
    #     SSW.SSWsteps: 50
    #     SSW.output: T
    #     SSW.ds_atom: 0.6
    #   system_files: [ h2o-64-explore ]

    #   potential:
    #     lammps: {}

    lammps:
      timestep: 0.0005
      sample_freq: 100
      nsteps: 2000
      ensemble: nvt

      system_files: [ h2o-64-explore ]

      explore_vars:
        TEMP: [ 330, ]
        PRES: [1]

      template_vars:
         POST_INIT: |
            neighbor 1.0 bin
            box      tilt large
         POST_READ_DATA: |
            change_box all triclinic

  select:
    model_devi:
        f_trust_lo: 0.2
        f_trust_hi: 0.4
        asap_options: {}  # use default options

  update:
    walkthrough:
      table: []
